version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    #image: portainer/portainer-ee:latest
    container_name: portainer

    restart: unless-stopped

    ports:
      - 8000:8000
      - 9443:9443
      #- 9000:9000
    #networks:
      #- proxy

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - </path/to/host/data>:/data

    #labels:
      #- "traefik.enable=true"

      #- "traefik.http.routers.portainer.entrypoints=http"
      #- "traefik.http.routers.portainer.rule=Host(`<wildcard.domain.example>`)"

      #- "traefik.http.routers.portainer-secure.entrypoints=https"
      #- "traefik.http.routers.portainer-secure.rule=Host(`<wildcard.domain.example>`)"
      #- "traefik.http.routers.portainer-secure.tls=true"
      #- "traefik.http.routers.portainer-secure.service=portainer"

      #- "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"

      #- "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      #- "traefik.http.services.portainer.loadbalancer.server.port=9000"

      #- "traefik.docker.network=proxy"

#networks:
  #proxy:
    #external: true
