version: '3'

services:
  zoffline:
    image: zoffline/zoffline:latest
    container_name: zoffline

    restart: unless-stopped

    ports:
      - 80:80
      - 443:443
      - 3022:3022/udp
      - 3023:3023

    environment:
      - TZ=Europe/Brussels
    volumes:
      - <path/to/host/storage>:/usr/src/app/zwift-offline/storage
