version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser

    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

    networks:
      - proxy

    environment:
      - PUID=<$ id -u>
      - PGID=<$ id -g>
    volumes:
      - </path/to/chosen/host/root>:/srv
      - </path/to/filebrowser.db/on/host>:/database.db
      - </path/to/settings.json/on/host>:/config/settings.json

   labels:
      - "traefik.enable=true"

      - "traefik.http.routers.filebrowser.entrypoints=http"
      - "traefik.http.routers.filebrowser.rule=Host(`<wildcard.domain.example>`)"
      - "traefik.http.middlewares.filebrowser-https-redirect.redirectscheme.scheme=https"

      - "traefik.http.routers.filebrowser-secure.entrypoints=https"
      - "traefik.http.routers.filebrowser-secure.rule=Host(`<wildcard.domain.example>`)"
      - "traefik.http.routers.filebrowser-secure.tls=true"

      - "traefik.http.routers.filebrowser.middlewares=filebrowser-https-redirect"

      - "traefik.http.routers.filebrowser-secure.service=filebrowser"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"

      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
