version: '3'

services:
  collabora:
    image: collabora/code
    container_name: collabora

    restart: unless-stopped
    cap_add:
      - MKNOD
    tty: true

    networks:
      - proxy
    ports:
      - 9980:9980
    expose:
      - "9980"

    environment:
      - domain=<wildcard.domain.example nextcloud>
      - 'dictionaries=en_US,nl_BE'
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=9980
      - VIRTUAL_HOST=<wildcard.domain.example of collabora>
      - "extra_params=--o:ssl.enable=false  --o:ssl.termination=true"

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.collabora.entrypoints=http"
      - "traefik.http.routers.collabora.rule=Host(`<wildcard.domain.example collabora>`)"
      - "traefik.http.middlewares.collabora-https-redirect.redirectscheme.scheme=https"

      - "traefik.http.routers.collabora-secure.entrypoints=https"
      - "traefik.http.routers.collabora-secure.rule=Host(`<wildcard.domain.example collabora`)"
      - "traefik.http.routers.collabora-secure.tls=true"

      - "traefik.http.routers.collabora.middlewares=collabora-https-redirect"

      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
