version: '3'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud

    restart: unless-stopped
    links:
      - mariadb

    networks:
      - proxy
    #ports:
      #- 8080:80

    environment:
      - MYSQL_PASSWORD=<password>
      - MYSQL_DATABASE=<db name>
      - MYSQL_USER=<user>
      - MYSQL_HOST=mariadb
    volumes:
      - </path/to/host/data>:/var/www/html
      - </path/to/external/data>:/data

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`<wildcard.domain.example>`)"
      - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https"

      - "traefik.http.routers.nextcloud-secure.entrypoints=https"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`<wildcard.domain.example>`)"
      - "traefik.http.routers.nextcloud-secure.tls=true"

      - "traefik.http.routers.nextcloud.middlewares=guacamole-https-redirect"

      - "traefik.http.routers.nextcloud-secure.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

      - "traefik.docker.network=proxy"

  mariadb:
    image: mariadb:10.5
    container_name: mariadb

    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW

    networks:
      - proxy

    environment:
      - MYSQL_ROOT_PASSWORD=<password>
      - MYSQL_PASSWORD=<password>
      - MYSQL_DATABASE=<db name>
      - MYSQL_USER=<user>
    volumes:
      - </path/to/host/datadb>:/var/lib/mysql
