version: '3'

services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      - PUID=1000
      - GUID=100
      - TZ=Europe/Brussels
    volumes:
      - </path/to/host/config>:/config
      - </path/to/host/data:/data
    labels:
      # Enable Traefik overlay
      - "traefik.enable=true"
      # Router: HTTPS for TLS
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.rule=Host(`<wildcard.domain.example>`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      # Service
      - "traefik.http.services.nextcloud.loadbalancer.server.port=443"
      - "traefik.http.services.nextcloud.loadbalancer.server.scheme=https"
      # Network
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
