version: "2.1"

services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard

    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    ports:
      - 51820:51820/udp

    environment:
      - PUID=<$ id -u>
      - PGID=<$ id -g>
      - TZ=Europe/Brussels
      - SERVERURL=<wildcard.domain.example>
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0,::/0
      - LOG_CONFS=true
    volumes:
      - </path/to/host/config>:/config
      - /lib/modules:/lib/modules
